### ISSUE TITLE
[FEAT] 스토리북 title 수정 및 Typography, Modal 스토리북 테스트 코드 작성

### ISSUE THREAD

**Issue by suminhan123** [Pi-plus/Pi-Plus-Client#111]
## 어떤 작업인지 설명해주세요
Modal, Popup, MathPopup 스토리북 테스트 코드 작성

## TODO
- [x] Typography 스토리북 테스트 코드 작성
- [x] Modal 스토리북 테스트 코드 작성
- [ ] ErrorMessage 스토리북 테스트 코드 작성
