### ISSUE TITLE
[FEAT] 수학 문제 주관식/객관식/분수 답안지 생성

### ISSUE THREAD

**Issue by suminhan123** [Pi-plus/Pi-Plus-Client#43]
## 어떤 작업인지 설명해주세요
수학 문제 주관식/객관식/분수 답안지 생성

## TODO
- [x] 주관식/객관식/분수 답 답안지 생성
- [x] 문제 타입에 맞게 답안지 분기 처리해 보여주기
- [x] 주관식 및 분수 경우 input 개수 동적으로 변화될 수 있게 로직 추가
