### ISSUE TITLE
[FEAT] 수학 답안지, 해설 답안 맞/틀림에 맞게 팝업 띄우기

### ISSUE THREAD

**Issue by suminhan123** [Pi-plus/Pi-Plus-Client#47]
## 어떤 작업인지 설명해주세요
수학 답안지, 해설 답안 맞/틀림에 맞게 팝업 띄우기

## TODO
- [x] 해설 답안과 답안지 응답이 맞았는 지 확인 로직 추가
- [ ] 해설 답안과 답안지 응답이 맞으면 CorrectPopup -> SolutionPopup
- [ ] 해설 답안과 답안지 응답이 틀리면 WrongPopup -> 다시 문제 풀기 또는 SolutionPopup
